### ISSUE TITLE
Memory leak in GUI on Windows caused by logging

### ISSUE THREAD

**Issue by speaker** [symless/synergy-core#4577]
Issue seen in Synergy 1.7.1 running on a windows 7 enterprise 64bit synergy server connected to an 10.10.3 iMac synergy client.

The synergy service continues to allocate physical memory (private) but doesn't appear to free the memory resource. Resource monitor can track the usage:
![synergy_mem_use](https://cloud.githubusercontent.com/assets/148108/7329110/baf6c626-ea90-11e4-9def-9fb5ab08badc.png)

The allocation appears related to switching from server to client and back. The problem appears worse when the switching back and forth is quick. (10 quick back and forth will consume more memory than slowly moving back and forth 10 times.)

**Comment by legonigel** [comment]
@speaker I can get to 100MB of memory usage on Linux in a not too much time as well. It only affects the synergy executable, not synergys. It is related to the logging. If you change the logging level to note, the memory usage decreases significanlty. See #4363 and #4341.

**Comment by legonigel** [comment]
It could also be related to #3335.

**Comment by andreialecu** [comment]
I've had memory usage issues with synergy for the past few years. Only thing I can do is completely uninstall it when I don't need it. Closing synergy itself does not clear the leaks, and the more uptime I have, the more they build up.

The leaks are extremely hidden, they don't even show up in taskmgr. I can only see them in RamMap, with thousands of synergys.exe and syntool.exe processes running and taking 20K each.

![Memory Leak](http://i.imgur.com/FzrV99Z.png)

**Comment by nbolton** [comment]
Duplicates #4341

**Comment by sccovey** [comment]
I have experienced this exact issue on Windows 10 running Synergy 1.10.1-stable-8941241e

RampMap is showing me thousands of syntool.exe and synergys.exe instances all sitting at 28k

the synergy log just keeps repeating the following lines:

```
synergys.exe: no configuration available
[2019-02-13T00:17:13] ERROR: failed to launch, error: process immediately stopped
[2019-02-13T00:17:13] INFO: backing off, wait=10s, failures=9432
[2019-02-13T00:17:23] INFO: starting new process
[2019-02-13T00:17:24] INFO: activeDesktop:Default
[2019-02-13T00:17:24] INFO: starting new process
[2019-02-13T00:17:24] INFO: drag and drop enabled
synergys.exe: no configuration available
[2019-02-13T00:17:25] ERROR: failed to launch, error: process immediately stopped
[2019-02-13T00:17:25] INFO: backing off, wait=10s, failures=9433
[2019-02-13T00:17:35] INFO: starting new process
[2019-02-13T00:17:35] INFO: activeDesktop:Default
[2019-02-13T00:17:35] INFO: starting new process
[2019-02-13T00:17:35] INFO: drag and drop enabled
```

**Comment by mazend** [comment]
I have experienced this exact issue on Windows 10 running Synergy 1.10.3-stable-ca35737a

![이미지 007](https://user-images.githubusercontent.com/23476117/87520969-a6a2e280-c6be-11ea-96c3-5a9a0e668165.png)

In addition I'm suffering from High cpu usage of **System** and **WMI Provider Host** processes with memory leakage.
I'm suspecting **synergy** program now.

The issue continuously happens after turning on computer for about 2~3 days even though I didn't run the synergy program.

Anyways I downloaded the latest synergy v. 1.11.1-stable-55ec3105.

I will check what would happen.

**Comment by charles-peter-nystrom** [comment]
I'm running into the old handle leak on 1.11.1-stable-55ec3105 running on Windows 10.0.18362, synergyd hit 280k handles in just under 10 hours.

**Comment by digitalsanity** [comment]
Debugging Windows 10 memory issues with 32GB RAM and traced it back to synergys also via rammap.

**Comment by andreacndn** [comment]
@digitalsanity we have fixed a number of memory leaks is 1.13.0, could you please test if the release candidate solves your problem?
https://rc.symless.com/synergy-1.13.0-rc2/synergy-1.13.0-rc2-windows-x64.msi

**Comment by mazend** [comment]
Hi All,
Here is my story.
The old version synergy v. 1.11.1-stable-55ec3105 didn't solve the problem.
I updated my ram from 16GB to 32GB but the issue still happened.
So.. I had deleted synergy long long ago.

I've just installed the latest version, 1.13.0.
I think I can know the result in 2~3 days.

**Comment by mazend** [comment]
I'm back.
I didn't turn off my laptop for two days and used the laptop during my waking hours.
It seems the issue was resolved.
The numbers of handles in `synergy.exe` and `synergyd.exe` are within the normal range.
I attacked related picitures.

![이미지 098](https://user-images.githubusercontent.com/23476117/102423416-543e6700-404c-11eb-8e12-ee645ce94022.png)
![이미지 097](https://user-images.githubusercontent.com/23476117/102423418-556f9400-404c-11eb-9ad8-cecb354fba7d.png)

**Comment by andreacndn** [comment]
@mazend thanks for the update! 
Looks great, will keep this issue open for few more days to be 100% sure it's all fixed.

**Comment by mazend** [comment]
Here is another test result.
I was going to keep my laptop turned on but.. unexpected windows update reboot my laptop.
so.. It's synergy idle test for 3 days.
It seems it's good. 

![이미지 062](https://user-images.githubusercontent.com/23476117/102995863-49606680-4565-11eb-9806-a933301d17e5.png)
![이미지 063](https://user-images.githubusercontent.com/23476117/102995867-4a919380-4565-11eb-8342-10cbcd91376c.png)

**Comment by andreacndn** [comment]
Thanks for the update!
I'll close the issue for now.
