### ISSUE TITLE
Mouse cursor drifting upwards

### ISSUE THREAD

**Issue by atrauzzi** [symless/synergy-core#5291]
- Surface Pro 3 running Windows 10 as the server.
- Ubuntu 15.10 as the client.

Whenever the mouse cursor is on the client (Ubuntu) screen, wiggling it side to side also causes it to drift upwards.  There's also a noticeable "resistance" when trying to move the mouse downwards.

**Comment by XinyuHou** [comment]
@atrauzzi 
Are you using high DPI on your Windows server?

**Comment by atrauzzi** [comment]
Surface pro is a high resolution display....?

**Comment by dawnerd** [comment]
Seeing this with win 10 on a 4k monitor with 1.5x scaling and the same model 4k monitor attached to a rMBP. Pretty much unusable. Larger mouse movements seem to work better, but things like selecting text are a real pain.

**Comment by NaderCHASER** [comment]
Seeing this with a Mac 10.12 server and WIN 10 client. The drift only occurs (for me) when the mouse is on the WIN 10 display.

Notes:
* iMac is 5K.
* WIN 10 is standard definition (1080 resolution).
* WIN 10 has Razer Synapse.

**Comment by XinyuHou** [comment]
Could you test this nightly please? This nightly includes high DPI fixes for Windows server.
http://symless.com/nightly?filter=synergy-v1.8.6-rc1-eb56683-Windows

**Comment by NaderCHASER** [comment]
Glad this is gaining traction. Any chance MacOS 10.12 Server suffers from the same issue?

I tried updating to the nightly on both my MacOS 10.12 server and WIN 10 client but it doesn't appear to have fixed anything.

**Comment by XinyuHou** [comment]
@NaderCHASER 
Thanks for your feedback. I have prioritized this ticket.

**Comment by aminor00** [comment]
I've just upgraded from MacOS 10.11 (El Capitan) to 10.12 (Sierra) on the server and still using Windows 7 on the client.

Prior to the upgrade to 10.12 all worked OK; there was no drift upward.  Nothing has changed on the Windows PC (no drivers, service packs etc)

Since installing 10.12 the drift has started and, as above, is rendering Synergy unusable.

I've tried synergy-v1.8.7-stable-9799e96-MacOSX-x86_64 and the nightly synergy-v1.8.8-rc1-4b913b5-MacOSX-x86_64 with their matching Windows releases, but both display the same problem.  I'm not sure if it's me but it *might* be slightly less intense on 1.8.8.

I've tried with and without SSL but it happens either way.  If you want me to test a build I'd be happy to help.

**Comment by rbalhorn** [comment]
Just upgraded to 10.12 server and have a 10.11 client, and am now seeing this :(

**Comment by aminor00** [comment]
I've just tried with:
* synergy-master-stable-c5b83ce-Windows-x64.msi
* synergy-master-stable-c5b83ce-MacOSX-x86_64.dmg

The drift problem still exists.  I've noticed that the mouse is drifting up and left, not just up.

**Comment by aminor00** [comment]
I have just tried a test with 1.8.8-stable-c30301e on the Windows 7 machine but this time acting as the server.
The client is now the MacOSX 10.12.3 Sierra box running the same level of software: 1.8.8-stable-c30301e.

With this configuration there is NO mouse movement problem.  Switching directly back to the Mac being the server with a Windows 7 client and the mouse movement issue comes straight back.

Unfortunately I cannot personally work this way around due to space and machine placement constraints.  Therefore Synergy remains unusable for me.

Maybe this info will help someone else.

**Comment by stingray88** [comment]
Having the same issues here. Was running fine with Synergy 1.8.6 on a 5K iMac (server) and a MacBook (client), with the iMac on El Capitan. As soon as I upgraded to Sierra on the iMac I'm having this issue... wish I could go back now.

**Comment by iaian7** [comment]
In addition to the exaggerated up+left movement, my tilt wheel is inverted when used on the client computer. Both computers are iMacs, both set to use standard ("unnatural") scrolling.

**Comment by rbalhorn** [comment]
I put on windows 10 via bootcamp and installed synergy and set it up as the server and my other macbook pro as client and the problem went away.  It seems this is an issue with using Sierra as server.

**Comment by aminor00** [comment]
This appears to be the same problem as listed in #5648

**Comment by robeberhardt** [comment]
5K iMac (server), MacBook Pro (client), both on Sierra
had the drift-up-and-left on client
fixed by https://github.com/symless/synergy/files/902511/synergy-v1.8.8-pr-5648-stable-1c1067d-MacOSX-x86_64.dmg.zip

**Comment by stingray88** [comment]
I was using version 1.8.8 before I made my last report... so unfortunately, this version doesn't fix it for everyone.

**Comment by aminor00** [comment]
@stingray88 Have you tried this specific version of 1.8.8?  It has code changes in it to resolve the issue reported in #5648 and is therefore different from the official 1.8.8 release.

**Comment by stingray88** [comment]
Ah my bad... didn't realize it was different. First impression, it might have fixed the issue! Thanks!

**Comment by NaderCHASER** [comment]
@robeberhardt Thanks for the heads up. @XinyuHou This appears to be fixed.

Only needed to update Mac server, not Windows client.

**Comment by iaian7** [comment]
Fixes the issue on my iMac to iMac setup too. Thanks for the links!

**Comment by aaronatframe** [comment]
Using Razer Synapse drivers, if I reduce the polling rate from 1000Hz to 125Hz, the up-and-left issue goes away.

**Comment by mejran** [comment]
Same issue when using 1.10.1. Goes away if I use the 1.8.8 build linked by robeberhardt.

The fix is in master but for some reason the builds do not include it which is frustrating since it means I'm stuck on 1.8.8.

**Comment by antevens** [comment]
Also having this issue with 1.10.1

**Comment by Blackskyliner** [comment]
Are there any problems, license related, that the fix which is included in the linked Version 1.8.8 did not make it into the most recent version? 

Better asked, what is the problem that the fix does not make it in the current version and/or is it because the code moved on in a technical way that the code which fixed the problem in that linked version, does not work anymore in the expected way?

Linking all current active Project Maintainers to this to raise attention. As most of paying users may not be able to use Synergy with the most recent version within a macosx environment because of this bug.

/cc @Jnewbon @nbolton @yurivict

**Comment by Jnewbon** [comment]
This is a duplicate of #5648

This has been fixed in #6469 which is in the 1.10.2 release #6497.

Website download links will be updated soon.

**Comment by nbolton** [comment]
Download: http://symless.test/synergy/downloads/list/s1

**Comment by Sqwashgaming** [comment]
Hi there, please pardon I don't mean to hijack as such. Just a quick question.

I saw this issue a while ago which was subsequent ally fixed by @putzworks, the issue I'm having is identical but on windows, since 2016.

Does anyone have any idea how to solve this drifting issue while in motion.

Apologies once again for posting this question here, I have exhausted all other options entirely. Cheers!
