### ISSUE TITLE
No horizontal scroll on Mac client with LInux host

### ISSUE THREAD

**Issue by posita** [symless/synergy-core#7220]
### Operating Systems ###

Server: Pop!_OS (`Linux ... 5.19.0-76051900-generic #202207312230~1660780566~22.04~9d60db1 SMP PREEMPT_DYNAMIC Thu A x86_64 x86_64 x86_64 GNU/Linux`)
Client: Mac OS 12.6 (`Darwin ... 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64 arm Darwin`)

### Synergy Version ###

Synergy 1 (server):
``` sh
% synergys --version
synergys 1.14.5-stable.b22-1b7140f2, protocol version 1.8
Copyright (C) 2012-2022 Symless Ltd.
Copyright (C) 2008-2014 Nick Bolton
Copyright (C) 2002-2014 Chris Schoenema
```
Synergy 2 (client):
``` sh
% /Applications/Synergy.app/Contents/MacOS/synergyc --version
synergyc 1.14.5-stable.b22-1b7140f2, protocol version 1.8
Copyright (C) 2012-2022 Symless Ltd.
Copyright (C) 2008-2014 Nick Bolton
Copyright (C) 2002-2014 Chris Schoeneman
synergyc: a server address or name is required
Try `synergyc --help' for more information.
```

### Steps to Reproduce ###

I am using a Logitech MX Anywhere 3, which, by default, scrolls horizontally when using the scroll wheel while pressing either thumb button. This works on my Linux host. However, when on the Mac client, I cannot scroll horizontally (it has no effect).

### Log URLs ###

For `Debug1` logging, with just the wheel, I get no output. However, for horizontal scrolling (wheel plus button), I get entries like the following.

Push wheel away from user while holding horizontal scroll button:

```
[2022-09-14T13:38:01] DEBUG1: recv mouse down id=5
[2022-09-14T13:38:01] DEBUG1: faking mouse button id: 4 press: pressed
[2022-09-14T13:38:01] DEBUG1: recv mouse up id=5
[2022-09-14T13:38:01] DEBUG1: faking mouse button id: 4 press: released
```

Pull wheel toward user while holding horizontal scroll button:

```
[2022-09-14T13:38:05] DEBUG1: recv mouse down id=4
[2022-09-14T13:38:05] DEBUG1: faking mouse button id: 3 press: pressed
[2022-09-14T13:38:05] DEBUG1: recv mouse up id=4
[2022-09-14T13:38:05] DEBUG1: faking mouse button id: 3 press: released
```

**Comment by posita** [comment]
When I connect the MX Anywhere 3 directly to the Mac, I don't observe any of this behavior and horizontal scrolling works normally.

I'm not sure if this is a red herring, but in `tmux` on the _client_, these events _appear_ to be translated to `MouseDown2Pane` events. I'm guessing this because attempts to scroll either direction with the horizontal mode button depressed result in `tmux` paste operations. The only mouse event I have bound to this is as follows:

```
% tmux list-keys | grep -i mouse | grep -i paste
bind-key    -T root         MouseDown2Pane       select-pane -t = \; if-shell -F "#{||:#{pane_in_mode},#{mouse_any_flag}}" { send-keys -M } { paste-buffer -p }
```

This pasting effect does _not_ happen on the Linux host, only on the Mac client.

**Comment by posita** [comment]
Not stale. Still a problem.

**Comment by posita** [comment]
Still an issue with Symless 3.

**Comment by nbolton** [comment]
> Still an issue with Symless 3 RC 2.

Thanks for the update. We will try to reproduce this.

**Comment by matthewtai** [comment]
Same issue observed on Windows 11 24H2 Server and macOS 15.4 Client
Mouse: MX Master 3
Was previously using barrier/input-leap

**Comment by sithlord48** [comment]
You may need to remap the mouse buttons on mac os.. iirc there is a work around in the wiki. maybe @nbolton  knows where that is  (if not in the wiki work arounds need to be added)

**Comment by nbolton** [comment]
Not sure, IIRC missing horizontal scroll is something we need to implement. Interestingly I think someone opened a PR recently in LAN Mouse for this: https://github.com/feschber/lan-mouse/pull/283

**Comment by below43** [comment]
I have this issue with Deskflow Windows 11 Client and Mac OS server which I believe is related.

The server is sending the correct information through, but the client interprets it as vertical scroll.

eg. [2025-07-16T14:58:00] DEBUG2: recv mouse wheel +480,+0

This should scroll right, not vertically.

**Comment by tbolish** [comment]
I posted a similar issue not realizing this already was a known proble with multiple platforms.  In my case, Windows 11 Server -> Mac OS 15.5 Server, as well as Mac OS 15.5 Server -> Windows 11 Client exhibit the same behavior....no scrolling on the other machine.

**Comment by sithlord48** [comment]
Horizontal scrolling does not work on my host. For me when i try to scroll horizontal it acts like page up / page down. If I am running deskflow and have the cursor on a client and try to do horizontal scrolling it seams to send page up / page down to the client . As far as i can tell on my set up its sending the correct action at least.

**Comment by sithlord48** [comment]
Note to self this maybe fixed by porting the https://github.com/debauchee/barrier/commit/9f15b1bcf2953acf609f7580463bf13cdb23d008 , need to add impl for EIScreen

**Comment by KoljaFrahm** [comment]
On 1.26.0 with a Fedora 42 x11 server and a windows client, the scroll wheel still doesnt work for me.

**Comment by KoljaFrahm** [comment]
Client:
[2026-03-02T11:13:36.296] DEBUG1: recv mouse down id=1
[2026-03-02T11:13:37.802] DEBUG1: recv mouse up id=1

Server:
[2026-03-02T11:13:57.347] DEBUG1: onMouseDown id=7
[2026-03-02T11:13:57.347] DEBUG1: send mouse down to "Kolja-SHIFTbook" id=7
[2026-03-02T11:13:57.347] DEBUG1: onMouseUp id=7
[2026-03-02T11:13:57.347] DEBUG1: send mouse up to "Kolja-SHIFTbook" id=7
Seems like this is the wrong button

**Comment by sithlord48** [comment]
Are you using any kind of mouse remaping software ? or  have you previously configured any software for your mouse Others users had issues because of applicaions like solaar that modify the mouse actions.

**Comment by KoljaFrahm** [comment]
I have solaar installed, but also if I kill solaar,  I have the same issue. The Debug message stays the same. How should the debug message look for the horizontal scroll?

**Comment by sithlord48** [comment]
Not sure but lest continue on #9488  as this user has has a similar issue with solaar installed.
